### ISSUE TITLE
Generated `Resolvers` interface not compatible with `IResolvers` from graphql-tools

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#124]
![image](https://user-images.githubusercontent.com/1567498/47142066-5f59a900-d2c2-11e8-9ef7-d7e045ed0aec.png)

Current workaround (add `as any`):

```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers: resolvers as any,
  context: { data },
})
``` 

My current understanding is that this is a limitation in `graphql-tools`. We should open an issue there.

**Comment by fedealconada** [comment]
any workaround until it is fixed?

**Comment by schickling** [comment]
See comment from above:

Current workaround (add `as any`):

```ts
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers: resolvers as any,
  context: { data },
})
```

**Comment by alexedev** [comment]
Same problem here

**Comment by rlux** [comment]
I am using makeExecutableSchema.
For me the incompatibility with IResolvers  was caused by a missing index signature. All generated resolvers should have it. As a workaround, I declare my resolvers as "...Resolvers.Type & { [key: string]: any } ".

**Comment by jasonkuhrt** [comment]
Duplicate of #15
