### ISSUE TITLE
Cannot override the Context name

### ISSUE THREAD

**Issue by OrKoN** [prisma/graphqlgen#154]
## Description

When I define a different class name for the context, graphqlgen still tries to import `Context` in the generated files.

## Steps to reproduce

1. Provide a different name for the context in graphqlgen.yml:

```
context: ./src/app/RequestContext.ts:RequestContext
```

## Expected results
In the generated file, the context is imported as following:

```
import { RequestContext } from '../app/RequestContext';
```

## Actual results
```
import { Context } from '../app/RequestContext';
```

## Versions
> Check your graphql-resolver-codegen by running:
> `graphql-resolver-codegen --version`

Version flag is not available in my version.

P.S. @schickling nice talk at GraphQL Finland

**Comment by Weakky** [comment]
Hey there, this was fixed by #145 but is not published yet 🙌

**Comment by schickling** [comment]
Just released `graphqlgen@0.2.0` 🎉

**Comment by OrKoN** [comment]
Does the context have to be an Interface? Mine is a class and I get an error: `Invalid context: interface 'RequestContext' not found in file './src/app/domain/RequestContext.ts'`

**Comment by Weakky** [comment]
Hey @OrKoN 👋,

That's a valid point here. At the moment, we only support interfaces.
Would you mind creating an issue for that?

Thanks!
