### ISSUE TITLE
How to work with optional values in models?

### ISSUE THREAD

**Issue by OrKoN** [prisma/graphqlgen#159]
Hi,

this is more of a question than a bug or a feature request. In my models, I have optional attributes (i.e. `attr?: string`) and in graphql schema I define it like `attr String`.  The problem here is that my model is basically `undefined | string` and the generated resolvers are `String | null` so the generated code cannot be compiled. In our projects, we avoid using `null` altogether, so my question is: should the default resolvers try to automatically convert undefined to `null`? Actually, I don't know if in GraphQL an attribute can be `undefined`, I guess it only supports `null`s.

**Comment by schickling** [comment]
Great question @OrKoN. I think this could indeed be handled by `graphqlgen`. So in case your model definition is `content?: string` (or the equivalent: `content: string | undefined`), the default resolver could look like this:

```ts
    content: (parent: Post) => parent.content === undefined ? null : parent.content,
```

**Comment by schickling** [comment]
Merged and released. Thanks a lot 🙌
