### ISSUE TITLE
Parent types are not generated - [ts] Property 'user' does not exist on type '{}'.

### ISSUE THREAD

**Issue by sapkra** [prisma/graphqlgen#163]
## Description
I build my server based on the example [prisma/graphql-prisma-typescript](https://github.com/prisma/graphql-prisma-typescript).
But with `graphqlgen` the AuthPayload is throwing type errors.

## Steps to reproduce
schema.graphql
```graphql
type AuthPayload {
  token: String!
  user: User!
}
```

AuthPayload.ts
```typescript
import { AuthPayloadResolvers } from "../generated/graphqlgen";

export const AuthPayload: AuthPayloadResolvers.Type = {
  ...AuthPayloadResolvers.defaultResolvers,

  token: (parent) => parent.token,
  user: (parent) => parent.user,
};
```

## Expected results
The parent type for `user` and `token` should be set to the types instead of empty objects.
Or maybe there is a different way to solve the problem?

## Actual results
```bash
[ts] Property 'token' does not exist on type '{}'.
[ts] Property 'user' does not exist on type '{}'.
```
because the parent type is an empty object:
```typescript
export interface Type {
    user: (
      parent: {},
      args: {},
      ctx: Context,
      info: GraphQLResolveInfo
    ) => UserNode | Promise<UserNode>;

    token: (
      parent: {},
      args: {},
      ctx: Context,
      info: GraphQLResolveInfo
    ) => string | Promise<string>;
  }
```

## Versions
- graphqlgen: 0.2.0-beta16
- OS name and version: Mac OS 10.14

**Comment by schickling** [comment]
Can you please try again with the latest version of `graphqlgen`? This should fix this problem.

**Comment by sapkra** [comment]
After the update to `0.2.1` the program suggested to add `AuthPayload` and `UserLookupInfo` to the `graphqlgen.yaml` but there is no generate typescript type for it.

Now I had to add the following lines to `src/resolvers/AuthPayload.ts`

```typescript
import { UserNode } from "../generated/prisma-client";

export interface AuthPayloadNode {
  token: string;
  user: UserNode;
}
```

and of cause this line to the `graphqlgen.yaml`
```yaml
AuthPayload: ./src/resolvers/AuthPayload.ts:AuthPayloadNode
```

I think it can be detected & generated automatically because it's already defined in the `src/schema.graphql`. Is it possible to add this functionality to `graphqlgen`?

**Comment by schickling** [comment]
Thanks a lot for the update. This is a different issue. Would you mind opening a new issue for this?
