### ISSUE TITLE
Support enums

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#168]
Right now enums don't seem to be supported. As a first TS implementation, we should go for string literals. So the following GraphQL `enum` would result in the following TS `type`:

```graphql
enum Color { Green, Red }
```

```ts
export type Color = "Green" | "Red"
```

The exported `type` in the `graphqlgen.ts` file should be outside of the generated namespaces. I suggest to put it right above the first namespace.

Note that this implementation does not yet support ["Internal enum values"](https://github.com/apollographql/apollo-server/blob/master/docs/source/features/scalars-enums.md#internal-values).

**Comment by timsuchanek** [comment]
Released in `0.2.8`
