### ISSUE TITLE
Namespaces not compatible with @babel/preset-typescript

### ISSUE THREAD

**Issue by affanshahid** [prisma/graphqlgen#208]
Currently the generated file uses namespaces which are not compatible with babel's typescript plugin. They don't plan to add support for namespaces, so there should be some configuration option which causes the generated file to not use namespaces. Is this possible?

**Comment by schickling** [comment]
This is also related to #115. Would love to see a proposal in there that doesn’t use namespaces.

**Comment by schickling** [comment]
We'll be moving forward with #115 which will remove namespaces!
