### ISSUE TITLE
Docs link isn't working

### ISSUE THREAD

**Issue by chanlito** [prisma/graphqlgen#210]
## Description

I'm trying to go to https://oss.prisma.io/graphqlgen/ but the browser says can't reach this page.

## Steps to reproduce

Open the link above.

## Expected results

To be able to access documentation page.

## Actual results

Page can't be reach.

## Versions

- graphqlgen: latest
- OS name and version: Microsoft using Edge

**Comment by schickling** [comment]
Thanks a lot for the headsup. We just fixed it. The docs should be back online.
