### ISSUE TITLE
Array fields in input types result in incorrectly generated typescript interface

### ISSUE THREAD

**Issue by ziegfried** [prisma/graphqlgen#225]
## Description

Generating typescript interfaces for array types do seem to always produce properties of type `string`.

## Steps to reproduce

Create an input containing a field with an array type:

```graphql
input TestInput {
  list: [String]
}
```

https://github.com/ziegfried/graphqlgen-input-type-bug

## Expected results

```typescript
  export interface TestInput {
    list: string[];
  }
```

## Actual results

```typescript
  export interface TestInput {
    list: string;
  }
```

## Versions

- graphqlgen: `0.2.12`

**Comment by ziegfried** [comment]
This seems to also apply to with all array fields in input types, not just `[String]`. For example:

```graphql
input TestInput {
  listref: [OtherInput]
}
```

**Comment by Weakky** [comment]
Hey,

Is it the CLI that is generating the wrong types when suggesting you typescript interfaces, or is it the actual code generation?

**Comment by ziegfried** [comment]
The actual code generation (ie. in the generated graphqlgen.ts namespace MutationResolvers).

**Comment by ziegfried** [comment]
Here's an example to reproduce: https://github.com/ziegfried/graphqlgen-input-type-bug

**Comment by DAB0mB** [comment]
Hey @ziegfried now I'm not a GraphQL expert but there's something which does exactly that and it just works. I've forked your repo and created a commit which patches that by switching to the alternative tool and I've tried to keep the changes to minimum: https://github.com/DAB0mB/graphqlgen-input-type-bug/commit/313ece33a25a05504e22fcc8c90c2c6ed597a7ef. Maybe you can use `graphql-code-generator` until they fix the issue...
