### ISSUE TITLE
Update a specific resolver via scaffold

### ISSUE THREAD

**Issue by divyenduz** [prisma/graphqlgen#23]
Currently, `scaffold` command does not override existing resolvers but has a `--force` or `-f` flag option to override all resolvers. 

Sometimes, we might want to update a specific resolver, the CLI should help in achieving that.

**Comment by jas99** [comment]
Hey @divyenduz @timsuchanek 
I have an idea, in this regard.
Lets says the following mutations were scaffolded.
```
export const Mutation: MutationResolvers.Type<TypeMap> = {
  signup: (parent, args) => {
    signup(parent,args);
  },
  login: (parent, args) => {
    login(parent,args);
  }
};
```
Rather then rewriting file, you should do delta update;

Let's say we have changed schema:
- Added logout mutation
- Removed signup mutation

Update should take old file and change it in following way
```
export const Mutation: MutationResolvers.Type<TypeMap> = {
  login: (parent, args) => {
    login(parent,args);
  }
  logout: (parent, args) => {
    throw new Error("Resolver not implemented");
  }
};
/*
  REMOVED
  signup: (parent, args) => {
    signup(parent,args);
  }
*/
```

Benefits
- By pushing the removals into comment section; there implementations will not be lost.
- Login mutation's implementation code is preserved.

**Comment by jas99** [comment]
Now thr is more then one way to achieve this, you can track schema changes from cache file, or loading header from existing files that will be updated.

Or you can come with something more novel that will preserve implementation code by atleast backing up rather then permanently deleting files; which risks loss of uncommitted work.

**Comment by divyenduz** [comment]
@jas99 : Thanks for the suggestion! Sounds like a good idea to me. Something like this is what I had in mind originally as well but we purposefully chose not to go the route of touching user written files yet and resorted to create issues for further discussions. 

I would wait to hear perspective from more members of the community before jumping to code this :)

**Comment by Weakky** [comment]
The new API should have solved this issue now
