### ISSUE TITLE
"scalar Update" is converted to wrong type

### ISSUE THREAD

**Issue by sapkra** [prisma/graphqlgen#239]
## Description
I'm implementing a mutation to upload images but while I was working on it I found out that `Upload` is converted to `string | null`.

I implemented the upload process similar to [this example](https://github.com/prisma/graphql-yoga/blob/master/examples/file-upload/index.ts).

## Steps to reproduce
schema.graphql
```graphql
scalar Update

type Mutation {
  uploadImage(
    file: Upload
  ): Image!
}
```

## Actual results
generated/graphqlgen.ts
```typescript
export interface ArgsUploadImage {
    file: string | null;
}
```
## Versions
- graphqlgen: 0.2.12
- OS name and version: Mac OS 10.14.1

**Comment by schickling** [comment]
Thanks a lot for reporting this issue. This is a current limitation and will be fixed by implementing #165. A PR is more than welcome!
