### ISSUE TITLE
Interfaces path to be friendlier

### ISSUE THREAD

**Issue by divyenduz** [prisma/graphqlgen#24]
Currently, the `scaffold` command gets the path to interfaces via `-i` argument. The value of this argument should be relative to `-o` (output) path supplied to `scaffold` command. 

While this is explicit, we can also support `-i` path as path from `src` directory and dynamically find out relative path.

**Comment by brikou** [comment]
I'm this kind of makefile:

```make
MAKEFLAGS += --no-builtin-rules
MAKEFLAGS += --no-builtin-variables

src/generated/resolvers.ts: src/schema.graphql
	yarn graphql-resolver-codegen interfaces \
		--output=$@ \
		--schema-path=$<

src/resolvers: src/schema.graphql src/generated/resolvers.ts
	yarn graphql-resolver-codegen scaffold \
		--force \
		--interfaces=$(shell python -c "import os.path; print os.path.splitext(os.path.relpath('"$(word 2, $^)"', '"$(word 1, $^)"'))[0]") \
		--output=$@ \
		--schema-path=$<
```

It should be quite easy to port the python part, WDYT?

**Comment by Weakky** [comment]
The new API should have fixed this issue now.
