### ISSUE TITLE
WhereInput Interface missing for multi level relations

### ISSUE THREAD

**Issue by sapkra** [prisma/graphqlgen#280]
## Description
I have a User which owns a Calendar and the Calendar has Entries.

`CalendarEntryWhereInput` is defined in `UserResolvers` & `CalendarResolvers` but it's missing in the `CalendarEntryResolver`.

It has to be in there because the `CalendarEntry` has a relation to the owning User.
Maybe one solution is to move these interfaces to a global scope so that all Resolvers are able to use the same interfaces.

## Actual results
Cannot compile because an error is thrown.
```bash
Cannot find name 'CalendarEntryWhereInput'
```

## Versions
- graphqlgen: 0.3.0
- OS name and version: Mac OS 10.14.1

**Comment by LawJolla** [comment]
Same issue, and for a TS neophyte like me, a show stopper.

**Comment by Esya** [comment]
I've got the same issue as well, for now my solution was to manually copy paste the interface declaration, but of course when I run graphqlgen next time I'll need to do it again..

**Comment by Weakky** [comment]
Hey everyone,

#267 should normally fix the problem and will land very soon with the next release 🙏

**Comment by LawJolla** [comment]
Thanks @Weakky !  In the interim, do you have a work around suggestion for a huge Prisma schema?  I'm unable to spin up the server.  Thanks for any suggestions!  (I'm new to Typescript, and thus far. can't figure out why I'm still using it)

**Comment by sapkra** [comment]
Downgrade graphqlgen until it's working. :wink:

**Comment by LawJolla** [comment]
@sapkra the older versions don't properly scaffold nested resolvers.  

Probably time to build out in JS and return when the project matures.

**Comment by JensMadsen** [comment]
if downgraded to 0.2.7 it kind of works for me :-)

**Comment by Weakky** [comment]
Hey 👋,

This should now be fixed by graphqlgen@0.4.0.

Could you please confirm? Thanks!
