### ISSUE TITLE
Skip file generation if content is the same

### ISSUE THREAD

**Issue by reuveniy** [prisma/graphqlgen#286]
## Description
When you run graphqlgen (gg) it overrides the files in the `generated` folder even if the new content is exactly the same as the old one. In some setup, when you have multiple plugins installed on your IDE, this could easily lead into CPU exhaustion as each plugin subscribe to file changes on the OS and will trigger an operation. This feature will skip writing file context if the file already has the exact same content.

## Additional context
In my specific setup, I am using TS auto compiler plugin for vscode, which listens to fs events and every time an ts file is changes it will automatically run tsc. when you have multiple scaffold file this is triggering a cascade rundown of tsc, which increase my build time by 2-3 minutes.

**Comment by reuveniy** [comment]
#287

**Comment by reuveniy** [comment]
#287

**Comment by jasonkuhrt** [comment]
> In my specific setup, I am using TS auto compiler plugin for vscode, which listens to fs events and every time an ts file is changes it will automatically run tsc. when you have multiple scaffold file this is triggering a cascade rundown of tsc, which increase my build time by 2-3 minutes.

This is a very strong use-case. I would like to prioritize this one.
