### ISSUE TITLE
Generated resolver types have typo "resolver" instead of "resolve"

### ISSUE THREAD

**Issue by rlux** [prisma/graphqlgen#438]
## Description
The generated resolver types contain a misspelling, when using fragments. Everything works fine when the resolver is a simple function, but in case that I need fragments, the resolve function is misspelled as "resolver" (This also makes it incompatible with the IResolver type from graphql). Using the key "resolver" makes the typescript compiler happy, but the resolve function is never called because of the wrong name. 

Example generated code:
`export type MyTypeResolver =
    | ((parent: MyType, args: {}, ctx: Context, info: GraphQLResolveInfo) => string | Promise<string>)
    | {
        fragment: string;
        resolver: (parent: MyType, args: {}, ctx: Context, info: GraphQLResolveInfo) => string | Promise<string>;
      };`

## Steps to reproduce
Use any graphql schema and generate the types with ./graphqlgen

## Expected results
The generated types should use the key "resolve".

## Actual results
The generated types use the key "resolve**r**".

## Versions
- graphqlgen: 0.6.0-rc5

**Comment by jasonkuhrt** [comment]
Closed by 8ff32835c1b4655b8bca264abb1134c00d3ab5e6

**Comment by jasonkuhrt** [comment]
Hey @rlux give [0.6.0-rc6](https://github.com/prisma/graphqlgen/releases/tag/0.6.0-rc6) a try.

**Comment by rlux** [comment]
@jasonkuhrt That was fast, thanks! It works great now :)
