### ISSUE TITLE
graphqlgen + Nexus?

### ISSUE THREAD

**Issue by colinmcd94** [prisma/graphqlgen#451]
Hi! So Nexus was publicly announced last week, and I'm curious how the scopes of the two projects overlap (or don't).

Nexus is focused on building typesafe schemas in a code-first way, whereas graphqlgen helps generate types for SDL schemas. If we're using Nexus for a new project, does this tool help us anymore?

**Comment by jasonkuhrt** [comment]
Hey @colinmcd94, nope graphqlgen is only useful for schema-first approach.
