### ISSUE TITLE
Make return of resolver dynamic

### ISSUE THREAD

**Issue by brikou** [prisma/graphqlgen#46]
Because it is ;)

**Comment by divyenduz** [comment]
@brikou : Can you please elaborate this with some examples? Or spec it out maybe.

**Comment by brikou** [comment]
We cannot know the return type because it is based on query. The only working typing is "any" or "unknown". Maybe runtime typings can help. The same applies also for " parent" param.

**Comment by divyenduz** [comment]
But we do know the return type of a Query via the schema right?

**Comment by divyenduz** [comment]
Can you give a counter example that would fail? Thanks!

**Comment by brikou** [comment]
@divyenduz The return type of a resolver is a subset of source (or parent, or object). So saying that post source includes fe: `id`, `title`, `body` is wrong if query is `{ post { id title } }`.

**Comment by schickling** [comment]
Right now `graphqlgen` is not yet supporting schema-delegation (e.g. with graphql-bindings). Please open a new issue in case that's what you've been looking for 🙏
