### ISSUE TITLE
Types for Subscriptions are not correct

### ISSUE THREAD

**Issue by abhiaiyer91** [prisma/graphqlgen#56]
Currently generating types for GraphQL subscriptions are the same as Query, Mutation. Subscription resolvers have a different structure.

**Comment by affanshahid** [comment]
Any update on this?

**Comment by schickling** [comment]
We should tackle this once #244 was merged. A PR for this would be highly appreciated 🙏

**Comment by samuela** [comment]
I just ran into this and it's a huge problem for me! What would be required to address it?
