### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by sapkra** [prisma/graphqlgen#64]
## Description
I'm getting the the following error.
I think the problem is that the index of `inputTypesMap` should be a string but in my case `typeToInputTypeAssociation[type.name]` is an array.

You can find the affected line [here](https://github.com/prisma/graphql-resolver-codegen/blob/master/src/generators/ts-generator.ts#L118).

## Steps to reproduce
I think it's reproducible by adding something like this to the `datamodel.prisma`:

```graphql
type Team {
  id: ID! @unique
  members: [User!]!
  calendar: [Calendar!]!
}
```
## Expected results
No error is thrown

## Actual results
Error in my console:
```bash
(node:72993) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at /Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/generators/ts-generator.js:80:282
    at Array.map (<anonymous>)
    at Object.generate (/Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/generators/ts-generator.js:80:10)
    at generateCode (/Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/index.js:87:28)
    at /Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/index.js:181:28
    at step (/Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/index.js:33:23)
    at Object.next (/Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/index.js:14:53)
    at fulfilled (/Users/sapkra/Documents/git/server/node_modules/graphql-resolver-codegen/dist/index.js:5:58)
    at <anonymous>
(node:72993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After that I also checked the content of the variables.
`type.name` = `'Team'`
`typeToInputTypeAssociation[type.name]` = `[ 'UserWhereInput', 'CalendarWhereInput' ]`

## Versions
- graphql-resolver-codegen: 0.3.0
- OS name and version: Mac OS 10.14

**Comment by gvonhagel** [comment]
I'm having this issue as well

**Comment by schickling** [comment]
Can you check whether you still have this problem with the latest version of `graphqlgen`?

**Comment by divyenduz** [comment]
I can confirm that this is still and issue, this PR fixes it: https://github.com/prisma/graphqlgen/pull/135

**Comment by jbiddulph** [comment]
I am also getting this error: TypeError: Cannot read property 'name' of undefined

```
<ion-item>
        <ion-label>Name</ion-label>
        <ion-input [(ngModel)]="item.name" placeholder="Name"></ion-input>
      </ion-item>
```

although this works:

`{{item?.name}}`
