### ISSUE TITLE
Implement helpful error messages

### ISSUE THREAD

**Issue by schickling** [prisma/graphqlgen#72]
## Process

- Design propsoal in [Figma](https://www.figma.com/file/JqwDQ723WSrg0zT7GKlKl461/graphqlgen-CLI?node-id=0%3A1)
- Implement in `graphqlgen`

## Cases

- [x] `graphqlgen.yml` file not found
- [x] Missing config option in `graphqlgen.yml`
- [x] Invalid GraphQL schema
- [x] Couldn't parse imported source definitions (i.e. `models`, `context`)
- [x] Model missing in `models` based on existing GraphQL type definition

**Comment by Weakky** [comment]
See #120, #121, #122, #123

**Comment by Weakky** [comment]
Lots of these helpful messages were implemented in #134, as part of the validation process
