### ISSUE TITLE
Compose a logo for graphqlgen

### ISSUE THREAD

**Issue by maticzav** [prisma/graphqlgen#79]
Hey 👋,

I think the logo should reflect the intent of this package; maybe we could have something connected with scaffolding or generation. I like the idea of a small construction site or a craftsman doing its job. Would love to hear other thoughts on this as well, maybe you think differently about the message of this package? 🙂

**Comment by kuldar** [comment]
I tried coming up with some options based on the GraphQL motiv style (as we had going for Middleware and OpenCRUD). Some are more abstract than others, in general, tried to convey the feeling of something being generated. 

Do we feel like we should be more literal in the icon? 
Maybe put more emphasis on Typescript / Type generation?

<img width="1604" alt="screenshot 2018-10-18 at 11 57 16" src="https://user-images.githubusercontent.com/1710629/47146994-85d11180-d2cd-11e8-87e8-89e7f7c369d3.png">

**Comment by schickling** [comment]
I really like the last logo proposal (v7). 💯 We should probably color it in the iconic GraphQL-pink.

What do others think?

**Comment by maticzav** [comment]
I really like `v5`. I think that's primarily because it somehow communicates the idea of a box which I connect with scaffolding. @kuldar could you maybe try something with a bit more touch of "construction site", more scaffold-ish?  `v7` seems a bit overly minimalistic when I think of it being placed in the README. Maybe we could add something? Perhaps even the colour could do! Just my thinking.

**Comment by koenpunt** [comment]
I like using the one of the more "original" looking, so 2, 4, or 6, but maybe do something with only partly coloring it pink, and then the other part gray, which then would give the feeling of being generated.

**Comment by schickling** [comment]
We ultimately opted for `v3`. Great work @kuldar! 🎉
