### ISSUE TITLE
Scaffold index.ts (Yoga) instead of including it in starter

### ISSUE THREAD

**Issue by maticzav** [prisma/graphqlgen#97]
Hey, I think we missed the point with the flow (`create-graphqlgen` + `graphqlgen-starter`). Let me explain;

I think `gqlgen` does a great job in terms of user experience. After `init` it spits only files which are necessary for generator to work. Once the generator is run, it scaffolds everything from based on the config. I think this is very important because users *don’t have to delete anything*. *Ever.* The major pain-point of `graphql-boilerplates` is that they give you functionality upfront, which you have to delete afterwards. Considering the fact that our prime audience aren’t beginners but rather experienced developers who want robustness of their system, we shouldn’t aim for predefined whatnots - local databases etc.. Rather, we should stick with the bare minimum and provide great foundation for scalable projects.

Additionally, one of our top points over the weekend considered immediate feedback in terms of functioning code. As I understood it, we want to make sure `graphqlgen` can be used immediately after running the generator. This is, we should also pack `yoga` or `apollo-server`. The plan was to include `yoga` in `graphqlgen-starter`, however, I think it’s misplaced there.

As I mentioned above, we aim at bare minimum in terms of files in the initially scaffolded project. Placing `index.ts` there requires pre-generated resolvers, which are not necessary for functioning `generator`. Therefore, I propose the following:

1. `graphqlgen-starter` should only pack `model.ts`, `graphqlgen.yml` and `schema.graphql`. This is _the_ foundation for every project we’ll scaffold. I think it might be beneficial to include one or two models as a sample in there but no more.
2. `graphqlgen.yml` should have a `server` option which could be either `yoga` or `apollo-server`. We can also default to Yoga. The main point here is that it should be scaffolded, instead of being included in `graphqlgen-starter`.

To reflect this, I’ve already added `no-generate` option to `create-graphqlgen` which prevents initial generation. I think this is very important design decision as everything is put bluntly in the flow of `npm init graphqlgen`; 
1. we ask for folder, 
1. we download code, 
1. we install dependencies, 
1. we generate models. 

*Every step is evident.* This way everyone understands what’s happening behind the scenes. Additionally, we’ll add even more descriptive final message which should be a great start for future exploration.

This, I think, is the bare minimum for Yoga to function properly.

```ts
import { GraphQLServer } from 'graphql-yoga'

import { resolvers } from './resolvers'

const server = new GraphQLServer({
  typeDefs: './schema.graphql',
  resolvers,
})

server.start(() => console.log('Server is running on http://localhost:4000'))
```

And ApolloServer, if we decide to include it as well;

```ts
import { ApolloServer } from 'apollo-server'
import { importSchema } from 'graphql-import'

import { resolvers } from './resolvers'

// Type definitions define the "shape" of your data and specify
// which ways the data can be fetched from the GraphQL server.
const typeDefs = importSchema("./schema.graphql")

// In the most basic sense, the ApolloServer can be started
// by passing type definitions (typeDefs) and the resolvers
// responsible for fetching the data for those types.
const server = new ApolloServer({ typeDefs, resolvers })

// This `listen` method launches a web-server.  Existing apps
// can utilize middleware options, which we'll discuss later.
server.listen().then(({ url }) => {
  console.log(`🚀  Server ready at ${url}`);
})
```

**Comment by schickling** [comment]
Thanks a lot for writing this up @maticzav. It's important to distinguish between the following flows/responsibilities:

1. **Generation**: Generating the main output file (e.g. `graphqlgen.ts`) which contains the type-definitions & default resolvers
2. **Scaffolding** (optional): Scaffolding resolver implementations & missing model definitions in a temporary folder for the sake of copy&pasting.
3. **Bootstrapping** (optional): Initially set up a fully-functioning GraphQL server project using `graphqlgen`.

1. + 2. are configured via `graphqlgen.yml`, 3. is handled in the `npm init graphqlgen` flow (via `create-graphqlgen`)

IMO choosing a GraphQL server implementation (Yoga, Apollo-Server, ...) is just relevant when bootstrapping but **not** for the scaffolding or generation flows. Therefore the server implementation should not be configured in the `graphqlgen.yml`.

Instead I suggest the server implementation should be selected interactively in the `npm init graphqlgen` flow or can be provided via a flag `npm init graphqlgen --server yoga`.

I'm feeling pretty strongly about this!
